name: Publish
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Version and Publish the changes
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Create cache folder
        run: mkdir -p /home/runner/.cache/yarn/v6
        continue-on-error: true
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        name: Setup Node v14.x
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          echo "access=public" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup Github Bot as a User
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish
        run: yarn run publish
